Repository FRONTENDSCHOOL5/final-17-breath-connect, pull requests merged in 2023-07, with the labels that each got.

#206 ♻️ Refactor: Styled Component
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/PostPage/PostDetailPageStyle.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/SearchPageStyle.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/UploadPageStyle.jsx
Labels: ♻️ refactor

#209 [Style] 로그인, 회원가입, 프로필 페이지 스타일 컴포넌트 분리
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPageStyle.jsx
  src/pages/ProfilePage/ProfileEdit/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfileEdit/ProfileEditPageStyle.jsx
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/ProfileSettingPage/ProfileSettingPageStyle.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/pages/SignupPage/SignupPageStyle.jsx
  src/pages/SnsLoginPage/SnsLoginPage.jsx
  src/pages/SnsLoginPage/SnsLoginPageStyle.jsx
  src/pages/SplashPage/SplashPage.jsx
  src/pages/SplashPage/SplashPageStyle.jsx
Labels: ♻️ refactor, 🎨 UI

#212 [Style] PostDetail 페이지 스타일 파일 정리
  src/pages/PostPage/PostDetailPageStyle.jsx
Labels: ♻️ refactor, 🎨 UI

#214 [Style] Modal 스타일 파일 정리
  src/components/common/Modal/IconPostModal.jsx
  src/components/common/Modal/IconPostModalStyle.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModalStyle.jsx
Labels: ♻️ refactor, 🎨 UI

#215 [Style] Alert 스타일 파일 정리
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Alert/LogOut.jsx
  src/components/common/Alert/LogOutStyle.jsx
Labels: ♻️ refactor, 🎨 UI

#217 [Refactor] 바텀 바 스타일 파일 분리 및 스멘틱 마크업
  src/components/Footer/BottomBarButton.jsx
  src/components/Footer/TabMenu.jsx
  src/components/Footer/style/FooterStyle.jsx
Labels: ♻️ refactor

#219 [Refactor] 프로필 페이지 스타일 파일 분리 및 시멘틱 마크업
  src/pages/ProfilePage/FollowCount.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
  src/pages/ProfilePage/style/FollowCountStyle.jsx
  src/pages/ProfilePage/style/ProfilePageStyle.jsx
  src/pages/ProfilePage/style/UserInfoStyle.jsx
Labels: ♻️ refactor

#218 Refactor: 맵 관련 스타일 파일 분리 및 시멘틱 마크업
  src/components/Map/DistanceInfo.jsx
  src/components/Map/MapComponent.jsx
  src/components/Map/MapDrawingManager.jsx
  src/components/Map/MapMenual.jsx
  src/components/Map/ToolBox.jsx
  src/components/Map/style/MapStyle.jsx
Labels: ♻️ refactor

#216 [Refactor] 헤더 스타일 분리 및 시멘틱 마크업
  src/components/Header/HeaderContainer.jsx
  src/components/Header/TopBasicNavHeader.jsx
  src/components/Header/TopChatNavHeader.jsx
  src/components/Header/TopListNavHeader.jsx
  src/components/Header/TopMainNavHeader.jsx
  src/components/Header/TopSearchNavHeader.jsx
  src/components/Header/TopUploadHeader.jsx
  src/components/Header/style/HeaderStyle.jsx
Labels: ♻️ refactor

#220 [Refactor] 팔로우페이지 스타일컴포넌트 분리 및 코드 수정
  src/components/common/User/Follow/Follow.jsx
  src/components/common/User/Follow/FollowStyle.jsx
  src/pages/FollowListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowerListPageStyle.jsx
  src/pages/FollowListPage/FollowingListPage.jsx
  src/pages/FollowListPage/FollowingListPageStyle.jsx
Labels: ♻️ refactor

#221 [Refactor] 스타일 파일 분리 및 코드 수정 (#204)
  src/components/common/Comment/ChatComment.jsx
  src/components/common/Comment/ChatCommentStyle.jsx
  src/components/common/User/Search/Search.jsx
  src/components/common/User/Search/SearchStyle.jsx
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatListPageStyle.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
  src/pages/ChatPage/ChatRoomPageStyle.jsx
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/pages/NotFoundPage/NotFoundPageStyle.jsx
Labels: ♻️ refactor

#225 [Feat] 프로필 사진 업로드 시 압축을 통해 이미지 최적화 기능 구현
  package-lock.json
  package.json
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
Labels: ✨ feat

#232 [Feat] 다크모드 기능 구현
  src/App.js
  src/assets/images/basic-profile-l-dark.svg
  src/assets/images/basic-profile-m-dark.svg
  src/assets/images/basic-profile-s-dark.svg
  src/assets/images/basic-profile-xs-dark.svg
  src/assets/images/home-logo-dark.svg
  src/assets/images/icon-404-dark.svg
  src/assets/images/login-logo-dark.svg
  src/assets/images/main-title-dark.svg
  src/assets/sprite/img-btn-dark.svg
  src/assets/sprite/spriteSheet.svg
  src/atoms/StylesAtom.js
  src/components/Footer/BottomBarButton.jsx
  src/components/Footer/FooterStyle.jsx
  src/components/Footer/TabMenu.jsx
  src/components/Header/BackButton.jsx
  src/components/Header/HeaderStyle.jsx
  src/components/Header/TopBasicNavHeader.jsx
  src/components/Header/TopMainNavHeader.jsx
  src/components/Header/TopUploadHeader.jsx
  src/components/Map/MapStyle.jsx
  src/components/common/Button/ButtonContainer.jsx
  src/components/common/Button/ButtonContainerStyle.jsx
  src/components/common/Input/InputStyle.jsx
  src/components/common/User/Follow/Follow.jsx
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatListPage/ChatListPageStyle.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/FeedPage/FeedComment.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FollowListPage/FollowerListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowerListPage/FollowerListPageStyle.jsx
  src/pages/FollowListPage/FollowingListPage/FollowingListPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/SnsLoginPage/SnsLoginPage.jsx
  src/pages/LoginPage/SnsLoginPage/SnsLoginPageStyle.jsx
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/pages/PostPage/PostDetailPage/PostDetailPage.jsx
  src/pages/PostPage/PostDetailPage/PostDetailPageStyle.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/FollowCount.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfilePage/ProfileEditPage/ProfileEditPageStyle.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/SearchPageStyle.jsx
  src/pages/SignupPage/EmailJoinPage/EmailJoinPage.jsx
  src/pages/SignupPage/EmailJoinPage/EmailJoinPageStyle.jsx
  src/pages/SignupPage/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignupPage/ProfileSettingPage/ProfileSettingPageStyle.jsx
  src/pages/SplashPage/SplashPage.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/UploadPageStyle.jsx
  src/routes/AppRouter.jsx
  src/styles/BasicLayout.jsx
  src/styles/DarkMode.jsx
  src/styles/Theme.jsx
Labels: 🎨 UI, ✨ feat

#233 [Feat] 검색페이지 debounce 구현
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨ feat

#235 [feat] 모달, 피드 edit 페이지 추가
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Modal/IconPostModal.jsx
  src/components/common/Modal/IconPostModalStyle.jsx
  src/components/common/Modal/ModalFunction.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModalStyle.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostDetailPage/PostDetailPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/UploadPage/UploadEditPage/UploadEditPage.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/routes/AppRouter.jsx
  src/utils/Apis.js
Labels: ✨ feat

#236 [Feat] 다크모드 버튼 추가
  src/App.js
  src/assets/images/moon.svg
  src/assets/images/sun.svg
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Button/DarkModeButton.jsx
  src/components/common/Button/DarkModeButtonStyle.jsx
  src/components/common/Modal/IconPostModalStyle.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModalStyle.jsx
  src/pages/PostPage/PostDetailPage/PostDetailPageStyle.jsx
  src/styles/DarkMode.jsx
Labels: 🎨 UI, ✨ feat

#238 [Refactor] Sprite 이미지
  src/assets/sprite/GlobalSprite.jsx
  src/assets/sprite/spriteSheet.svg
  src/components/Footer/BottomBarButton.jsx
  src/components/Header/BackButton.jsx
  src/components/Header/TopBasicNavHeader.jsx
  src/components/Header/TopChatNavHeader.jsx
  src/components/Header/TopMainNavHeader.jsx
  src/components/common/Comment/ChatComment.jsx
  src/pages/FeedPage/FeedComment.jsx
  src/pages/LoginPage/SnsLoginPage/SnsLoginPage.jsx
  src/pages/PostPage/PostPage.jsx
Labels: ♻️ refactor

#239 [Refactor] Modal, Alert 개선
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModalStyle.jsx
Labels: ♻️ refactor

#241 [Refactor] 오전 작업 진행
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
Labels: ♻️ refactor

#242 [Refactor] 코멘트 작성시 코멘트 카운트 안올라가는 이슈 해결
  src/pages/PostPage/PostDetailPage/PostDetailPage.jsx
Labels: ♻️ refactor

#243 ♻️ Refactor: 팔로우 기능 개선 (#237)
  src/pages/ProfilePage/UserInfo.jsx
Labels: ♻️ refactor
