Repository FRONTENDSCHOOL5/final-17-breath-connect, pull requests merged in 2023-06, with the labels that each got.

#14 [Style]: 공통 컴포넌트 Comment 추가
  src/components/common/Comment/Comment.jsx
Labels: 🎨 UI

#15 [Style]: 공통 컴포넌트 Input 추가
  src/components/common/Input/Input.jsx
Labels: 🎨 UI

#25 [Assets]: 메인 아이콘 추가
  src/assets/images/basic-profile-l.svg
  src/assets/images/basic-profile-m.svg
  src/assets/images/basic-profile-s.svg
  src/assets/images/basic-profile-xs.svg
  src/assets/images/breath_connect.png
  src/assets/images/full-logo.svg
  src/assets/images/home-logo.svg
  src/assets/images/icon-404.svg
  src/assets/images/login-logo.svg
  src/assets/images/main-title.svg
Labels: 📂 assets

#29 [Feat] 페이지 라우터 연결
  package-lock.json
  package.json
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatPage.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
  src/routes/AppRouter.jsx
Labels: ✨ feat

#30 [Style]: GlobalStyle, Theme 컬러 속성 값 추가
  .eslintrc.json
  src/App.js
  src/pages/LoginPage/LoginPage.jsx
  src/styles/GlobalStyle.jsx
  src/styles/Theme.jsx
Labels: 🎨 UI

#35 [Style] Layout 컴포넌트 app.js에 추가
  src/App.js
  src/styles/BasicLayout.jsx
Labels: 🎨 UI

#37 [Refactor] AppRouter에 불필요한 주석 제거 및 코드 컨벤션 적용
  src/routes/AppRouter.jsx
Labels: ♻️ refactor

#40 [Fix] BasicLayout 컴포넌트 수정
  src/App.js
Labels: 🐛 bug

#45 [Feat] 404페이지 UI 마크업 및 기능 구현
  src/pages/NotFoundPage/NotFoundPage.jsx
Labels: 🎨 UI, ✨ feat

#47 [Feat] 게시물 업로드 페이지 UI 마크업 구현
  src/pages/PostPage/PostPage.jsx
Labels: 🎨 UI, ✨ feat

#46 [Refactor] 공통 컴포넌트 Header 코드 수정
  src/components/Header/TopUploadHeader.jsx
Labels: ♻️ refactor

#50 ♻️ Refactor: ButtonContainer 불필요한 코드 삭제 (#48)
  src/components/common/Button/ButtonContainer.jsx
Labels: ♻️ refactor

#49 ♻️ [Refactor] 공통 컴포넌트 Header 코드 컨벤션에 맞게 수정 (#48)
  src/components/Header/HeaderContainer.jsx
  src/components/Header/TopChatNavHeader.jsx
  src/components/Header/TopListNavHeader.jsx
  src/components/Header/TopMainNavHeader.jsx
  src/components/Header/TopSearchNavHeader.jsx
Labels: ♻️ refactor

#52 [Fire] 게시물 페이지 < 게시물 업로드 페이지 코드 (삭제)
  src/pages/PostPage/PostPage.jsx
Labels: 🔥 fire

#51 [Feat] 게시물 업로드 페이지 UI 마크업 구현
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI, ✨ feat

#55 [Feat] 로그인 페이지 UI 및 기능 구현
  package-lock.json
  package.json
  src/components/common/Input/Input.jsx
  src/index.js
  src/pages/LoginPage/LoginPage.jsx
  src/recoil/LoginData.js
  src/utils/Apis.js
Labels: 🎨 UI, ✨ feat

#56 [Feat] Splash 페이지 구현
  src/pages/SnsLoginPage/SnsLoginPage.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: 🎨 UI, ✨ feat

#59 [Refactor] HeaderContainer컨벤션 적용 및 보더 오류 수정
  src/components/Header/HeaderContainer.jsx
Labels: ♻️ refactor

#54 [Feat] 404페이지 UI 마크업 및 기능 구현 (#53)
  src/pages/NotFoundPage/NotFoundPage.jsx
Labels: 🎨 UI, ✨ feat

#61 [Feat] 프로필 페이지 구현 (#57)
  src/pages/ProfilePage/FollowCount.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
Labels: 🎨 UI

#62 [Feat] Feed 페이지 UI 구현
  src/pages/FeedPage/Feed.jsx
  src/pages/FeedPage/FeedNoUser.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/PostDetail.jsx
Labels: 🎨 UI

#67 [Style] GlobalStyle, Theme 컬러 속성 값 추가
  src/styles/Theme.jsx
Labels: 🎨 UI

#66 [Refactor] 공통 컴포넌트 Header 수정 (Search)(컨벤션 적용 및 props 추가)
  src/components/Header/TopSearchNavHeader.jsx
Labels: ♻️ refactor

#63 [Feat] 회원가입 페이지 UI 마크업 및 기능 구현
  src/atoms/LoginAtom.js
  src/atoms/UserAtom.js
  src/components/common/Input/Input.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/recoil/LoginData.js
  src/routes/AppRouter.jsx
  src/utils/Apis.js
Labels: 🎨 UI, ✨ feat

#69 [Refactor] Footer 수정 (TabMenu) (스타일)
  src/components/Footer/BottomBarButton.jsx
  src/components/Footer/TabMenu.jsx
Labels: ♻️ refactor, 🎨 UI

#73 [Refactor] 게시물 업로드 페이지 수정
  src/pages/UploadPage/UploadPage.jsx
Labels: ♻️ refactor

#72 [Add] 검색 페이지 경로 추가
  src/routes/AppRouter.jsx
Labels: 📝 docs

#71 [Feat] 검색 페이지 UI 마크업 및 기능 구현
  src/components/Header/TopSearchNavHeader.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ❓question, ♻️ refactor, 🎨 UI, ✨ feat

#81 [Style] 게시물 업로드 페이지 (글자 수 세기) 기능 추가
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI, ✨ feat

#84 ✨ Feat: Map 컴포넌트 UI 및 기능 구현 (#83)
  src/components/Map/DistanceInfo.jsx
  src/components/Map/FeedMap.jsx
  src/components/Map/GetLocation.jsx
  src/components/Map/MapDrawingManager.jsx
Labels: 🎨 UI

#82 🎨 Style: 공통 컴포넌트 User 수정 (#80)
  src/components/common/User/Follow/Follow.jsx
Labels: 🎨 UI

#89 [Feat] 회원가입 초기 프로필 세팅 페이지 UI 및 기능 구현
  src/atoms/LoginAtom.js
  src/atoms/UserAtom.js
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/utils/Apis.js
Labels: 🎨 UI, ✨ feat

#91 [Refactor, Style] atom 변경에 따른 코드 수정 및 에러메시지 초기화, margin 값 변경
  src/pages/LoginPage/LoginPage.jsx
Labels: ♻️ refactor, 🎨 UI

#94 [Feat] 공통 컴포넌트 Modal UI 구현
  src/components/common/Modal/IconPostModal.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/PostModal.jsx
Labels: 🎨 UI, ✨ feat

#97 [Feat] 채팅방 UI 구현
  src/assets/images/chat-img.png
  src/components/common/Comment/ChatComment.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
Labels: 🎨 UI, ✨ feat

#98 [Style] Sns 로그인 페이지 UI 구현
  src/pages/SnsLoginPage/SnsLoginPage.jsx
Labels: 🎨 UI

#99 🎨 Style: Feed 페이지 UI 및 기능 구현(#58)
  src/pages/FeedPage/Feed.jsx
  src/pages/FeedPage/FeedComment.jsx
  src/pages/FeedPage/FeedDetail.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/PostDetail.jsx
Labels: 🎨 UI

#102 [Refactor, Style] 회원가입 및 프로필 세팅 에러 메시지 초기화 및 margin 속성값 수정
  src/assets/sprite/img-btn.svg
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignupPage/SignupPage.jsx
Labels: ♻️ refactor, 🎨 UI

#104 [Feat] 채팅페이지와 채팅룸 연결
  src/pages/ChatPage/ChatListPage.jsx
  src/routes/AppRouter.jsx
Labels: ✨ feat

#105 [Style] FollowList페이지 UI 구현
  src/components/common/User/Follow/Follow.jsx
  src/pages/FollowListPage/FollowListPage.jsx
Labels: 🎨 UI, ✨ feat

#106 ✨ Feat: api를 이용해 데이터를 전달 받아 띄우는 기능 추가 (#58)
  src/pages/FeedPage/Feed.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/ProfilePage/FollowCount.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨ feat

#100 [Feat] 업로드 페이지 API 연결
  src/components/Header/TopUploadHeader.jsx
  src/components/Map/FeedMap.jsx
  src/components/Map/MapDrawingManager.jsx
  src/pages/UploadPage/UploadMap.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/utils/Apis.js
Labels: ✅ test, ✨ feat

#108 [Refactor] 채팅리스트/채팅방 페이지 비율 조정
  src/assets/images/chat-img.png
  src/pages/ChatPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage.jsx
Labels: ♻️ refactor

#109 [Refactor] Footer TabMenu 위치 고정
  src/components/Footer/TabMenu.jsx
Labels: ♻️ refactor

#110 [Refactor] 검색 페이지 기능 개선
  src/pages/SearchPage/SearchPage.jsx
Labels: ♻️ refactor

#111 [Feat] api 호출을 위한 함수 추가
  src/utils/Apis.js
Labels: ✨ feat

#112 [Add] ReadMe 내용 추가
  README.md
Labels: 📝 docs

#116 [Style] FeedPage API 변수명 수정
  src/pages/FeedPage/FeedPage.jsx
Labels: 🎨 UI

#115 [Style] FollowListPage 불러올 컴포넌트 경로 수정
  src/pages/FollowListPage/FollowListPage.jsx
Labels: 🎨 UI

#114 [Style] ProfilePage API 변수명 수정
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🎨 UI

#118 [Refactor] Modal 기능 구현
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/LogOut.jsx
  src/components/common/Modal/IconPostModal.jsx
  src/components/common/Modal/PostModal.jsx
Labels: ♻️ refactor, ✨ feat

#119 [Feat] API 연결 및 업로드, 피드 공동작업
  src/pages/FeedPage/Feed.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProfilePage/FollowCount.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨ feat

#127 [Feat] 프로필 페이지 본인 확인 기능 추가
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨ feat

#123 [Add] README.md 문서 추가
  README.md
Labels: 📝 docs

#125 [Feat] 피드 페이지 스크롤 기능및 갯수 제한
  src/pages/FeedPage/FeedPage.jsx
Labels: ✨ feat

#122 [Feat] 팔로워/팔로잉페이지 API연결
  src/components/common/User/Follow/Follow.jsx
  src/pages/FollowListPage/FollowListPage.jsx
  src/pages/FollowListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowingListPage.jsx
Labels: ✨ feat

#130 [Feat] 업로드 입력값들 일시, 시간, 작성 글, 위치 주소 변환
  src/pages/FeedPage/Feed.jsx
  src/routes/AppRouter.jsx
Labels: ✨ feat

#132 [Refactor] 팔로우 기능 개선
  src/components/common/User/Follow/Follow.jsx
  src/pages/FollowListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowingListPage.jsx
Labels: ♻️ refactor

#134 [Fix] tabnav 버튼 재렌더링 이슈 해결
  src/components/Footer/BottomBarButton.jsx
  src/components/Footer/TabMenu.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/routes/AppRouter.jsx
Labels: 🐛 bug, ♻️ refactor

#135 [Style] Upload 페이지 스타일 변경
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI

#137 [Feat] 피드의 PostPage 상세 페이지 이동 및 라우터 변경
  src/components/common/Comment/Comment.jsx
  src/pages/FeedPage/Feed.jsx
  src/pages/FeedPage/FeedDetail.jsx
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/routes/AppRouter.jsx
  src/utils/Apis.js
Labels: ✨ feat

#139 ✨ Feat: 맵 관련 컴포넌트 추가 및 수정 (#138)
  src/components/Map/DistanceInfo.jsx
  src/components/Map/FeedMap.jsx
  src/components/Map/Indecator.jsx
  src/components/Map/MapComponent.jsx
  src/components/Map/MapDrawingManager.jsx
  src/components/Map/MapMenual.jsx
  src/components/Map/ToolBox.jsx
Labels: ♻️ refactor, 🎨 UI, ✨ feat

#140 [Refactor] 팔로우 이미지 오류 해결
  src/components/common/User/Follow/Follow.jsx
  src/pages/FollowListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowingListPage.jsx
  src/routes/AppRouter.jsx
Labels: ♻️ refactor

#142 [Feat] 상세 페이지 댓글 기능 구현 및 파일 이름 변경
  src/pages/FeedPage/FeedComment.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostDetailPage.jsx
Labels: ⚙️ chore, ✨ feat

#143 [Feat] 프로필 페이지 Modal 기능 추가
  src/components/Header/TopBasicNavHeader.jsx
  src/components/common/Alert/Alert.jsx
  src/components/common/Modal/IconPostModal.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨ feat

#141 [Refactor] 검색 페이지 API 코드 수정 및 key값 에러 해결
  src/pages/SearchPage/SearchPage.jsx
  src/utils/Apis.js
Labels: ♻️ refactor

#146 [Style] 피드 상세 페이지 댓글 컨테이너 너비 조정
  src/pages/PostPage/PostDetailPage.jsx
Labels: 🎨 UI

#148 [Feat] 모달 기능 구현 1차
  src/pages/FeedPage/FeedComment.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
Labels: ✨ feat

#150 [Style] PostPage 스타일 수정
  src/pages/PostPage/PostPage.jsx
Labels: 🎨 UI

#154 [Refactor] PostPage 컨텐츠 넘치는 현상 해결
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI

#153 [Style] 업로드 페이지 TabMenu 추가
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI

#155 [Style] 검색페이지 스타일 수정
  src/pages/SearchPage/SearchPage.jsx
Labels: 🎨 UI

#159 ♻️ Refactor: 포스트 페이지에서 맵 컴포넌트 보이게 수정 (#158)
  src/pages/PostPage/PostPage.jsx
Labels: ♻️ refactor

#160 ♻️ Refactor: 포스트 페이지에서 맵 컴포넌트 보이게 수정 (#156)
  src/pages/FeedPage/FeedPage.jsx
Labels: ♻️ refactor

#162 [Style] Modal 스타일 수정
  src/components/common/Alert/Alert.jsx
  src/components/common/Alert/LogOut.jsx
  src/components/common/Modal/IconPostModal.jsx
  src/pages/PostPage/PostDetailPage.jsx
Labels: 🎨 UI

#163 [Style] TabMenu 스타일 수정
  src/components/Footer/TabMenu.jsx
Labels: 🎨 UI

#166 [Feat] 업로드 페이지 경로 수정
  src/pages/UploadPage/UploadPage.jsx
Labels: ✨ feat

#164 [Refactor, Feat] 피드 지도 코드 수정 및 Post Detail 페이지 참여하기 기능 추가
  src/components/Map/FeedMap.jsx
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/utils/Apis.js
Labels: ♻️ refactor, ✨ feat

#167 [Refactor] post 디테일 페이지 댓글 코드 수정 (#165)
  src/pages/FeedPage/FeedComment.jsx
  src/pages/PostPage/PostDetailPage.jsx
Labels: ♻️ refactor

#168 [Style] 모달 페이지, TabMenu 스타일 수정
  src/components/Footer/TabMenu.jsx
  src/components/common/Modal/PostModal.jsx
Labels: 🎨 UI

#171 [Fix] 로그인 -> 홈화면 이동시 안보이는 오류 수정
  src/pages/LoginPage/LoginPage.jsx
Labels: 🐛 bug, ♻️ refactor

#170 [Fix] 로그인 -> 홈화면 이동시 안보이는 오류 수정
  src/pages/FeedPage/FeedPage.jsx
  src/utils/Apis.js
Labels: 🐛 bug, ♻️ refactor

#173 [Fix] 회원가입 이메일 중복 확인 시, 입력값마다 api 함수 호출 에러
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignupPage/SignupPage.jsx
  src/utils/Apis.js
Labels: 🐛 bug

#175 [Fix] 프로필 페이지 사진 및 경로 수정
  src/components/common/Modal/IconPostModal.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/ProfilePage/UserInfo.jsx
Labels: 🐛 bug

#178 [Fix] 프로필 수정 페이지 오류 수정
  src/pages/ProfilePage/ProfileEdit/ProfileEditPage.jsx
  src/utils/Apis.js
Labels: 🐛 bug

#180 [Refactor] 맵 크기 및 버튼 수정
  src/components/Map/MapDrawingManager.jsx
  src/components/Map/ToolBox.jsx
Labels: ♻️ refactor

#183 [Refactor] postDetailPage 하단 잘리는 부분 해결
  src/pages/PostPage/PostDetailPage.jsx
Labels: ♻️ refactor

#184 [Refactor] 팔로잉/팔로워페이지 코드 수정
  src/pages/FollowListPage/FollowerListPage.jsx
  src/pages/FollowListPage/FollowingListPage.jsx
Labels: ♻️ refactor

#186 [Fix] 하단바 눌렀을 시 본인 프로필 안보이던 에러 수정
  src/pages/ProfilePage/ProfilePage.jsx
Labels: 🐛 bug

#189 [Fix] Modal ~ FeedPage
  src/components/common/Alert/Alert.jsx
  src/components/common/Modal/IconPostModal.jsx
  src/components/common/Modal/PostModal.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostDetailPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/utils/Apis.js
Labels: 🐛 bug

#188 [Refactor] PostPage 마크업 수정
  src/pages/FeedPage/FeedComment.jsx
  src/pages/PostPage/PostPage.jsx
Labels: ♻️ refactor

#181 [Refactor] 로그인 상태에서 홈페이지로 redirect
  src/pages/LoginPage/LoginPage.jsx
Labels: ♻️ refactor

#190 [Fix] 일부 페이지 수정 (종합)
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: 🐛 bug

#194 [Style] Map UI 변경
  src/components/Map/DistanceInfo.jsx
  src/components/Map/MapDrawingManager.jsx
Labels: 🎨 UI

#191 [Style] 검색 페이지 Input UI 수정
  src/components/Header/TopSearchNavHeader.jsx
Labels: 🎨 UI

#195 [Refactor] 업로드 페이지 map 설명 추가
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI

#196 [Refactor] 업로드 페이지 map 코드 추가
  src/pages/UploadPage/UploadPage.jsx
Labels: 🎨 UI

#197 [Feat] UserInfo 버튼 경로 설정
  src/pages/ProfilePage/UserInfo.jsx
Labels: ✨ feat

#198 [Style] 로딩 컴포넌트 추가 -> map 로딩 페이지
  src/components/Map/Indecator.jsx
  src/components/Map/MapDrawingManager.jsx
  src/components/common/Loading/Loading.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/ProfilePage/ProfilePage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: ♻️ refactor, 🎨 UI

#199 [Chore] 파비콘 추가
  public/favicon.ico
  public/index.html
Labels: ⚙️ chore

#200 [Fix] 에러 메시지와 성공 메시지 겹침 현상 버그 해결
  src/pages/SignupPage/SignupPage.jsx
Labels: 🐛 bug
